In [17]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [18]:
df = pd.read_csv('Health_Data.csv')

In [19]:
df.head()

,Start,Finish,Active Calories (kcal),Body Fat Percentage (%),Body Mass Index (count),Dietary Calories (cal),Distance (mi),Flights Climbed (count),Lean Body Mass (lb),Number of Times Fallen (count),Oxygen Saturation (%),Resting Calories (kcal),Steps (count),Weight (lb)
0,20-Dec-2014 00:00,21-Dec-2014 00:00,0.0,0.0,0.0,0.0,2.955856,6.0,0.0,0.0,0.0,0.0,0.0,0.0
1,21-Dec-2014 00:00,22-Dec-2014 00:00,0.0,0.0,0.0,0.0,2.272411,7.0,0.0,0.0,0.0,0.0,0.0,0.0
2,22-Dec-2014 00:00,23-Dec-2014 00:00,0.0,0.0,0.0,0.0,2.947684,10.0,0.0,0.0,0.0,0.0,0.0,0.0
3,23-Dec-2014 00:00,24-Dec-2014 00:00,0.0,0.0,0.0,0.0,3.662284,14.0,0.0,0.0,0.0,0.0,0.0,0.0
4,24-Dec-2014 00:00,25-Dec-2014 00:00,0.0,0.0,0.0,0.0,2.474685,9.0,0.0,0.0,0.0,0.0,0.0,0.0

In [20]:
workouts = pd.read_csv('my_workouts.csv')

In [21]:
workouts.head()

,Type,Start,End,Duration,Distance,Average Heart Rate,Max Heart Rate,Average Pace,Average Speed,Average Cadence,Active Energy,Total Energy,Elevation Ascended,Elevation Descended,Weather Temperature,Weather Humidity
0,Outdoor Running,2021-01-13 09:52,2021-01-13 10:26,0:34:23,4.849530,114.931398,130.0,0:07:05,8.459564,294.952441,429.200,531.425,41.07,NaN,7.0,61.0
1,Other,2021-01-11 12:34,2021-01-11 12:42,0:07:18,NaN,122.968750,185.0,NaN,NaN,NaN,91.970,137.553,NaN,NaN,9.0,82.0
2,Outdoor Walking,2021-01-10 15:58,2021-01-10 16:09,0:10:31,0.757444,94.238095,112.0,0:13:53,4.320372,205.560360,63.440,112.274,9.04,NaN,8.0,86.0
3,Outdoor Running,2021-01-10 15:33,2021-01-10 15:58,0:24:52,3.242148,117.484979,153.0,0:07:40,7.820193,283.268025,295.637,350.925,29.00,NaN,8.0,86.0
4,Outdoor Walking,2021-01-10 09:32,2021-01-10 10:39,0:52:28,4.309139,71.099371,125.0,0:12:10,4.927681,199.568123,307.086,482.287,50.64,NaN,6.0,97.0

In [22]:
calories_burned = workouts['Active Energy'].mean()

In [23]:
print(calories_burned)

259.0290735163861

In [24]:
distance_traveled = workouts['Distance'].mean()

In [25]:
print(distance_traveled)

4.316604166812204

In [26]:
outdoor_running = workouts['Type'] == 'Outdoor Running'

In [27]:
number_of_outdoor_running_workouts = outdoor_running.value_counts()

In [28]:
print(number_of_outdoor_running_workouts)

False    1099
True       41
Name: Type, dtype: int64